# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Blog
    url: blog/
    weight: 20
  - name: Documentation
    weight: 30
    url: docs/
    hasChildren: true
  - parent: Documentation
    name: "Installation Guide"
    url: "docs/installation/"
  - parent: Documentation
    name: "Quickstart Guide"
    url: "docs/quickstart/"
  - parent: Documentation
    name: "User Manual"
    url: "docs/manual/"    
  - name: Roadmap
    url: roadmap/
    weight: 40
  - name: Contribute
    weight: 50
    url: "contribute/"
  - name: Resources
    weight: 60
    hasChildren: true
  - parent: Resources
    name: Use Cases
    url: portfolio/
  - parent: Resources
    name: Workshops
    url: workshop/
  - name: Links
    weight: 70
    hasChildren: true
  - parent: Links
    name: "Youtube"
    url: "https://www.youtube.com/@KaotoIO"
  - parent: Links
    name: "Linked In"
    url: "https://www.linkedin.com/groups/12998297/"
  - parent: Links
    name: "Github"
    url: "https://github.com/KaotoIO/"
  - parent: Links
    name: "Zulip Chat"
    url: "https://camel.zulipchat.com/#narrow/stream/441302-kaoto"
  - parent: Links
    name: "Discussion Forums"
    url: "https://github.com/orgs/KaotoIO/discussions"
  - parent: Links
    name: "Planning Board"
    url: "https://github.com/orgs/KaotoIO/projects/14"
    
