# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# removes the copyright stuff from Hugo Blox
i_am_a_sponsor: true

# Appearance
appearance:
  mode: system
  color: sky

# SEO
marketing:
  seo:
    site_type: SoftwareApplication
    local_business_type: ''
    org_name: 'Kaoto'
    description: 'Kaoto is an open source visual editor for Apache Camel integration routes and data transformation, designed to improve the productivity of integration developers in a low-code / no-code way.'
    twitter: 'KaotoIO'
  analytics:
    google_analytics: ''  
    google_tag_manager: ''
  verification:
    google: ''  
    baidu: ''

# SEO Defaults
params:
  description: 'Open source visual designer for Apache Camel integrations. Low-code editor with 300+ components, Enterprise Integration Patterns and Kamelets. Available as VS Code extension.'
  images: 
    - 'logo-kaoto.png'  
  keywords:
    - Apache Camel
    - Integration Designer
    - Visual Editor
    - Low Code
    - VS Code Extension
    - Kamelets
    - Enterprise Integration Patterns
    - Open Source
    - EIP
    - Camel Routes

# Social Media / Open Graph
social:
  twitter: 'KaotoIO'
  github: 'KaotoIO'

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo-kaoto.png"
#    button:
#      enable: true
#      text: "GitHub"
#      url: "https://github.com/KaotoIO/?target=_blank"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: 'Â© {year} - <a href="https://camel.apache.org">Apache Camel</a> is a trademark of the <a href="https://apache.org">Apache Software Foundation</a>.<br/><br/><div style="background-color:#17181c;padding:20px;margin:auto;border-radius: 9px;"><a href="https://redhat.com" target="_blank" rel="noopener noreferrer">![Red Hat Logo](redhat-sponsor.png)</a></div>'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
